### ISSUE TITLE
Error happened at the last step

### ISSUE THREAD

**Issue by jinlei787** [c64-dev/Cozmo.AI#2]
<img width="482" alt="Screen Shot 2020-05-16 at 10 17 12 AM" src="https://user-images.githubusercontent.com/43528155/82108022-6a0a4780-975e-11ea-9b62-0cf50f2ef7e7.png">

**Comment by c64-dev** [comment]
This error is happening when you haven't installed the requests module on your system.
Install the module by running 
`pip3 install requests`

and then try the main program again.

**Comment by jinlei787** [comment]
Thank you for ur message; I has installed requests. However,  can not install geckodriver,  I install Chromedriver instead. Is there any problems with Chromedrive?

**Comment by c64-dev** [comment]
At the moment the program is coded to use firefox in headless mode which needs geckodriver. 
Chromedriver unfortunately cannot work with Firefox (it works with Chrome browser). 

The program _could_ be made to work with chrome browser but it would require some rewriting, which at the moment is out of the scope of the project. 
At some point I will rework the code to be able to function with either Firefox or Chrome, but for now you need to install geckodriver. 
What problem are you having to install it?

**Comment by c64-dev** [comment]
Since there has been no replies from the OP I will move ahead to close the issue and consider it resolved.
